In [ ]:
Numpy Array Bilgileri

1- dtype : arraydeki elemanların veri tipi
2- size : arraydeki toplam eleman sayısı 
3- ndim : arrayin boyut sayısı 
4 - shape : arrayin satır-sütun bilgisi 

In [7]:
import numpy as np

npArray= np.array([1,2,3,4,5])
print(npArray)
print(npArray.dtype)
print(npArray.size)
print(npArray.ndim)
print(npArray.shape)

[1 2 3 4 5]
int32
5
1
(5,)


In [9]:
npArray2D = np.random.randint(0,50,(5,5))
print(npArray2D)
print(npArray2D.dtype)
print(npArray2D.size)
print(npArray2D.ndim)
print(npArray2D.shape)

[[31 42 32  0 28]
 [42 10 15  0  2]
 [ 1 22 35 40 27]
 [ 6 37 10 44  3]
 [ 6 27 47 25 12]]
int32
25
2
(5, 5)
