In [8]:
import numpy as np
nparray = np.arange(1,10)
nparray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
nparray+=5
nparray

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
nparray-=5
nparray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

TypeError: '>' not supported between instances of 'list' and 'int'