In [1]:
import numpy as np

nparray = np.arange(1,10)
nparray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
nparrayAdd = np.add(nparray,5)
nparrayAdd

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
nparraySubstract = np.subtract(nparray,5)
nparraySubstract

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [5]:
nparrayMultiply = np.multiply(nparray,5)
nparrayMultiply

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [6]:
nparrayDivide = np.divide(nparray,5)
nparrayDivide

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [7]:
nparrayPower = np.power(nparray,5)
nparrayPower

array([    1,    32,   243,  1024,  3125,  7776, 16807, 32768, 59049],
      dtype=int32)

In [8]:
nparrayMod = np.mod(nparray,5)
nparrayMod

array([1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int32)

In [9]:
nparray.mean()

5.0

In [10]:
nparray.sum()

45

In [11]:
nparray.min()

1

In [12]:
nparray.max()

9