In [ ]:
array elemanlarına erişmek

1- index yardımıyla elemanlara erişmek
2- parçalama yardımıyla eleman alt kümelere erişmek

In [4]:
import numpy as np

npArray = np.array([1,2,3,4,5])
print(npArray)
print(npArray[0])
print(npArray[-1])
print(npArray[2])
print(npArray[-3])

npArray[0] = 0
print(npArray)

[1 2 3 4 5]
1
5
3
3
[0 2 3 4 5]


In [12]:
npArray2d = np.random.randint(0,50,(5,5))
print(npArray2d)
print(npArray2d[0][2])

npArray2d[0][0] = 61
print(npArray2d)


[[ 9 23  4 39 34]
 [42 46 40 13 34]
 [25  8  9 49 29]
 [19 47 25 35 35]
 [13 49 17 43 20]]
4
[[61 23  4 39 34]
 [42 46 40 13 34]
 [25  8  9 49 29]
 [19 47 25 35 35]
 [13 49 17 43 20]]


In [14]:
nparray = np.arange(0,50)
print(nparray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [15]:
nparray[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
nparray[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [17]:
nparray[:15:5]


array([ 0,  5, 10])

In [18]:
nparray[15::5]

array([15, 20, 25, 30, 35, 40, 45])