In [ ]:
hazır fonksiyonlar 

1- reshape() numpy arrayi yeniden boyutlandırmak için kullanılır.
2- concatenate() numpy arrrayleri birleştirmek için kullanılır.
3- split() numpy arrayi bölmek-ayırmak için kullanılır.
4- sort() numpy arrayi sıralamak için kullanılır. 

In [12]:
import numpy as np

nparray = np.arange(1,10)
nparray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
nparray3d = nparray.reshape((3,3))
nparray3d

nparray9d = nparray.reshape((9,1))
nparray9d

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [16]:
a = np.arange(0,10)
b = np.arange(10,20)
c = np.concatenate([a,b])
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
a = np.array([[1,2,3,4,5],[1,2,3,4,5]])
b = np.array([[6,7,8,9,10],[6,7,8,9,10]])
c = np.concatenate([a,b])  # alt alta ekleme yapılır. 
d = np.concatenate([a,b],axis=1)   # yan yana ekleme yapılır.
print(c)
print(d)

[[ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


In [20]:
nparray = np.arange(1,10)
a,b,c = np.split(nparray,3)
print(a)
print(b)
print(c)

[1 2 3]
[4 5 6]
[7 8 9]


In [21]:
nparray2d = np.random.randint(0,50,(4,4))
nparray2d

array([[20,  8, 39, 23],
       [27,  5, 48, 16],
       [29, 49, 46, 41],
       [32, 24, 42, 14]])

In [23]:
a,b=np.vsplit(nparray2d,[2])
print(a)
print(b)

array([[20,  8, 39, 23],
       [27,  5, 48, 16]])

In [25]:
c,d = np.hsplit(nparray2d,[2])
print(c)
print(d)

[[20  8]
 [27  5]
 [29 49]
 [32 24]]
[[39 23]
 [48 16]
 [46 41]
 [42 14]]


In [27]:
randomarray = np.random.randint(0,50,(1,10))
print(randomarray)
sortedarray = np.sort(randomarray)
print(sortedarray)

[[30 41 27  5 45 45 39 46 16  1]]
[[ 1  5 16 27 30 39 41 45 45 46]]


In [28]:
randomarray2d = np.random.randint(0,50,(5,10))
sortedarray2d = np.sort(randomarray2d)    # yatayda sıralama 
sortedarray2deks = np.sort(randomarray2d,axis=0)   # dikeyde sıralama 


In [29]:
print(sortedarray2d)

[[ 1  4  8  9 23 23 25 26 43 44]
 [ 0  3 11 22 32 35 43 43 45 47]
 [ 5  6  8 10 12 12 19 20 32 47]
 [ 3  6  8 16 22 23 25 26 44 45]
 [ 1  3  7 17 25 25 37 40 44 49]]


In [30]:
print(sortedarray2deks)

[[20  4 22  0  5  6 11  1  3  1]
 [22  8 23  7  8  6 12 12  3  3]
 [23 26 32  8 26 25 16 25  9 19]
 [44 40 43 10 37 25 17 43 35 23]
 [49 47 44 45 45 32 43 44 47 25]]
