In [ ]:
Numpy Array

1- direkt liste gibi tanımlanır
2- zeros() fonksiyonu ile tüm elemanları 0 olan dizi tanımlarız.
3- ones() fonksiyonu ile tüm elemanları 1 olan dizi tanımlarız.
4- full() fonksiyonu ile tüm elemanları aynı olan dizi tanımlarız.
5- arange() fonksiyonu ile belirli aralıkta, sabit artış ile dizi tanımlarız.
6- lnspace() fonksiyonu ile belirli aralıkta eleman sayısına göre sabit bir artış ile dizi tanımlarız.
7- randint() fonksiyonu ile belirli aralıkta rastgele eleman üreterek dizi tanımlarız.

In [2]:
import numpy as np

npArrayList = np.array([1,2,3,4,5])
print(type(npArrayList))
print(npArrayList)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [4]:
npZeroArray = np.zeros(5,dtype="int")
print(type(npZeroArray))
print(npZeroArray)

<class 'numpy.ndarray'>
[0 0 0 0 0]


In [10]:
npZeroArray2D = np.zeros((5,5),dtype="int") # np.zeros(kaçlık dizi, veri tipi)
print(type(npZeroArray2D))
print(npZeroArray2D)

<class 'numpy.ndarray'>
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [11]:
npOneArray = np.ones(5,dtype="int")
print(type(npOneArray))
print(npOneArray)

<class 'numpy.ndarray'>
[1 1 1 1 1]


In [12]:
npOneArray2D = np.ones((5,5),dtype="int")  # np.ones(kaçlık dizi, veri tipi)
print(type(npOneArray2D))
print(npOneArray2D)

<class 'numpy.ndarray'>
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [15]:
npFullArray = np.full((5,5),4)   # np.full(kaçlık dizi,hangi sayı)
print(type(npFullArray))
print(npFullArray)


<class 'numpy.ndarray'>
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [19]:
npArrangeArray = np.arange(0,50,5)  # np.arrange(başlangıç,bitiş,artış miktarı)
print(type(npArrangeArray))
print(npArrangeArray)

<class 'numpy.ndarray'>
[ 0  5 10 15 20 25 30 35 40 45]


In [20]:
npLinspaceArray = np.linspace(0,50,10)  # np.linspace(başlangıç,bitiş, eleman sayısı)
print(type(npLinspaceArray))
print(npLinspaceArray)

<class 'numpy.ndarray'>
[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [24]:
npRandomArray = np.random.randint(0,50,(5,5))  # np.random.randomint(başlangıç,bitiş,dizi boyutu)
print(type(npRandomArray))
print(npRandomArray)

<class 'numpy.ndarray'>
[[29 26  2 34 33]
 [22 17 34  8 15]
 [33 14 22 37 12]
 [ 8 10 16 15 39]
 [39 29 12 16 41]]
